apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: node-test-deployment
  labels:
    app: node-test-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-test-pod-label
  template:
    metadata:
      labels:
        app: node-test-pod-label
    spec:
      containers:
      - name: node-test-container
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
        image: coramdeo0620/node-test-app
        ports:
        - containerPort: 8080
        imagePullPolicy: Always